CREATE TABLE USER
(
  ID           INTEGER AUTO_INCREMENT NOT NULL,
  ACCOUNT_ID   VARCHAR(100),
  NAME         VARCHAR(50),
  TOKEN        VARCHAR(36),
  GMT_CREATE   BIGINT,
  GMT_MODIFIED BIGINT
);
COMMENT ON COLUMN USER.ACCOUNT_ID IS '用户id';
COMMENT ON COLUMN USER.NAME IS '用户名';
COMMENT ON COLUMN USER.TOKEN IS 'token';
COMMENT ON COLUMN USER.GMT_CREATE IS '创建时间';
COMMENT ON COLUMN USER.GMT_MODIFIED IS '修改时间'
